#!/bin/bash

(
    cd src/

    ./configure \
        --enable-link-time-optimization \
        --with-modules \
        --with-cairo \
        --without-sound \
        --with-pdumper=yes \
        --with-x-toolkit=lucid \
        --with-imagemagick \
        --with-harfbuzz \
        --with-json
)
