#!/bin/bash
BUILD_DIR=$(pwd)/build
EMACS_DIR=$(pwd)/emacs

mkdir -p "$BUILD_DIR"

set -eEo pipefail
trap 'printf "\n%s\n" "config failed"' ERR

(
    printf "config dir: %s\n" $EMACS_DIR
    printf "build dir: %s\n" $BUILD_DIR

    cd "$EMACS_DIR" || exit 2

    time ./configure \
         --prefix="$BUILD_DIR" \
         --exec-prefix="$BUILD_DIR" \
         --with-cairo \
         --with-harfbuzz \
         --with-native-compilation \
         --with-pgtk \
         --with-modules \
         --with-pdumper=yes \
         --with-imagemagick \
         --with-json \
         --without-sound \
         --without-pop
)

printf "======================"
printf "\n%s\n" "configuration complete"
printf "======================"
printf "\n\n"
