#!/bin/bash
BUILD_DIR=$(pwd)/build

(
    cd emacs/ || exit 2

    ./configure \
     --prefix="$BUILD_DIR" \
     --exec-prefix="$BUILD_DIR" \
     --without-sound \
     --with-cairo \
     --with-harfbuzz \
     --with-modules \
     --with-native-compilation \
     --with-pdumper=yes \
     --with-imagemagick \
     --with-json
)
