#!/bin/bash

set -eEo pipefail
trap 'printf "\n%s\n" "compilation failed"' ERR

BUILD_DIR=$(pwd)/build

(
    cd emacs/ || exit 2
    time make NATIVE_FULL_AOT=1 -j4 all prefix="$BUILD_DIR" exec_prefix="$BUILD_DIR"
    make -j4 install prefix="$BUILD_DIR" exec_prefix="$BUILD_DIR"
)

printf "\n%s\n" "compilation completed ✓"
