#!/bin/sh

# tag mails from mailing-lists
notmuch tag -new +lists +lists/emacs-devel +unread -- tag:new and to:emacs-devel@gnu.org
notmuch tag -new +lists +lists/emacs-help  +unread -- tag:new and to:help-gnu-emacs@gnu.org
notmuch tag -new +lists +lists/emacs-misc  +unread -- tag:new and to:emacs-tangents@gnu.org
notmuch tag -new +lists +lists/emacs-misc  +unread -- tag:new and to:emacs-humanities@gnu.org
notmuch tag -new +lists +lists/emacs-bugs  +unread -- tag:new and to:"/@debbugs[.]gnu[.]org/"

# tag mails from build servers
notmuch tag -new +builds +unread -- tag:new and from:builds@circleci.com
notmuch tag -new +builds +unread -- tag:new and from:notifications@github.com

# drafts and sent mail are not new
notmuch tag -new -- tag:new and tag:draft
notmuch tag -new -- tag:new and tag:sent

# mails sent from different muas are still sent by me
notmuch tag -new +sent -- tag:new and from:jensecj@gmail.com

# mute new mails from muted threads
notmuch tag -new -unread +muted -- $(notmuch search --output=threads tag:muted)

# ignores
# notmuch tag -new -unread +deleted -- tag:new and from:spam@spam.com

# remaining mail goes to the inbox
notmuch tag +inbox +unread -new -- tag:new
