#!/bin/sh

INTERFACE="wlan0"

STRENGTH=$(grep $INTERFACE /proc/net/wireless | awk '{print $4}' | tr -d '.')
ICON=""
if [ -z "$STRENGTH" ]; then
    ICON=""
elif [ "$STRENGTH" -lt -70 ]; then
    ICON=""
elif [ "$STRENGTH" -lt -60 ]; then
    ICON=""
elif [ "$STRENGTH" -lt -50 ]; then
    ICON=""
else
    ICON=""
fi

if ip a | grep "mullvad" > /dev/null; then
    printf "[$ICON]" # it's in a box, get it?
elif ip a | grep "wg" > /dev/null; then
    printf "[$ICON]"
else
    printf "$ICON"
fi

echo ""
