# zmodload zsh/zprof

export DOTFILESHOME=$HOME/.dotfiles
export ZSHHOME=$DOTFILESHOME/zsh

# add things to PATH
paths=("$DOTFILESHOME/bin" "$HOME/.cargo/bin")
for p in $paths; do
    export PATH=${PATH}:${p}
done

# load plugins
for p in $ZSHHOME/plugins/*.sh; do
    source $p
done

export EDITOR="em"

eval $(dircolors -b $DOTFILESHOME/dircolors)
eval $(keychain --eval --quiet --agents ssh ~/.ssh/github)

source $ZSHHOME/keybindings.zsh
source $ZSHHOME/aliases.zsh
source $ZSHHOME/options.zsh
source $ZSHHOME/jens-theme.zsh

# save our command history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# load the auto completion system
autoload -Uz compinit
compinit

# show the selected item in the menu
zstyle ':completion:*' menu select
# setup an autocompletion style (case-insensitive)
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# zprof
